name: Pipeline Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: |
          docker build -t hello-world .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          docker run hello-world python -c "from app import app; print(app.url_map)"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run App
        run: |
          docker run -d -p 5001:5000 --name my-app hello-world
        env:
          PORT: 5001
