name: Pipeline Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t hello-world .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run --rm hello-world \
            python -c "from app import app; print('App importado com sucesso!')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run -d -p 5001:5000 --name my-app hello-world
