name: Pipeline Hello World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t my-hello-world .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test application
        run: |
          docker run --rm my-hello-world \
            python -c "from app import app; print('App import test passed!')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name running-app my-hello-world
