name: Pipeline Confiável
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          docker build -t reliable-app .
          
      - name: Test
        run: |
          docker run --rm reliable-app \
            python -c "import flask; print('Flask version:', flask.__version__)"

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build again for deploy
        run: docker build -t my-hello-world .
      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name running-app my-hello-world
